name: Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Check code with Black
      uses: psf/black@master
